--- # My first yaml playbook
- hosts: demo
  user: venkatesh
  sudo: yes
  connection: ssh
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Install HTTPD server on centos 7
      action: yum name='{{ pkgname}}' state=installed

