--- # Outline to playbook Translation
- hosts: demo
  user: venkatesh
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: date/time stamp for playbook start
      raw: /usr/bin/date > /home/venkatesh/playbook_start.log
    - name: Install the apache web server
      yum: pkg=httpd state=latest
      notify: Restart the HTTPD
    - name: install client software - telnet
      yum: pkg=telnet state=latest
    - name: log all the packages installed
      raw: yum list installed > /home/venkatesh/installed.log
    - name: date/time stamp for playbook end
      raw: /usr/bin/date > /home/venkatesh/playbook_end.log

  handlers:
        - name: Restart the HTTPD  # this has to match the notify name  #
          action: service name=httpd state=restarted
