--- # Running tasks parallel
- hosts: all
  user: venkatesh
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Apache
      action: yum name=httpd state=installed
      async: 300
      poll: 3
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD  # ihis has to match the notify name  #
      action: service name=httpd state=restarted

