--- # Running tasks parallel
- hosts: all
  user: venkatesh
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install Apache
      action: yum name=httpd state=installed
      run_once: true
      delegate_to: localhost   # This is used to notify specific machine name  #
      notify: Restart HTTPD
  handlers:
    - name: Restart HTTPD  # this has to match the notify name  #
      action: service name=httpd state=restarted
