--- # Creating EC2 Instances in AWS
- hosts: localhost
  become: yes
  become_user: ansible
  connection: local
  gather_facts: no
  tasks:
  - name: Install python-boto library  # prerequisite 
    pip: name=boto
  - name: Create AWS Instances
    ec2:
     key_name: "testkey"
     instance_type: "t2.micro"
     image: "ami-c58c1dd3"
     wait: true
     region: "us-east-1"
