--- # master playbook for web services
- hosts: all
  user: venkatesh
  sudo: yes
  connection: ssh
  roles:
    - { role: redhatwebservers, when: ansible_os_family == "RedHat" }
    - { role: debianwebservers, when: ansible_os_family == "debian" }
