--- # Running tasks waitfor
- hosts: local
  user: venkatesh
  connection: ssh
  gather_facts: no
  sudo: yes
  tasks:
    - name: Install Apache on centos
      yum: pkg=httpd state=latest
    - name: wait for the service to start listening on port 80
      wait_for:
        port: 80
        state: started
